<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="VerPedidos.aspx.cs" Inherits="WebApplication1.Admin.VerPedidos" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1 class="center">Pedidos</h1>
    <div class="row margin-top-50">
        <div class="col-6">
            <asp:Panel ID="Panel1" runat="server">
                <asp:Label ID="MensagemA" runat="server"></asp:Label>
                <h2>Pedido de Adoção</h2>
                <asp:GridView ID="GridView1" AutoGenerateColumns="true" CellPadding="8" AutoGenerateDeleteButton="true" OnRowDeleting="GridView1_RowDeleting" DataKeyNames="Codigo" runat="server"></asp:GridView>
            </asp:Panel>
        </div>
        <div class="col-6">
            <asp:Panel ID="Panel2" runat="server">
                <asp:Label ID="MensagemV" runat="server"></asp:Label>
                <h2>Pedido de Voluntario</h2>
                <asp:GridView ID="GridView2" AutoGenerateColumns="true" CellPadding="8" AutoGenerateDeleteButton="true" OnRowDeleting="GridView2_RowDeleting" DataKeyNames="Codigo" runat="server"></asp:GridView>
            </asp:Panel>
        </div>
    </div>
</asp:Content>
